#!/bin/bash
echo "Updating software packages..."
if [ -f /etc/redhat-release ]; then
  sudo yum update -y
  sudo yum clean all
else
  sudo apt-get update
  sudo apt-get dist-upgrade -y
  sudo apt-get -f install
  sudo apt-get autoremove --purge -y
  sudo apt-get clean
fi
COMPOSER=$(command -v composer)
if [ ! -z "$COMPOSER" ]; then
  echo ""
  echo "Updating composer..."
  composer self-update
  echo ""
  echo "Updating composer global packages..."
  composer global update
fi
NVM_DIR="$HOME/.nvm"
if [ -d $NVM_DIR ]; then
  echo ""
  echo "Updating nodejs..."
  [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm
  nvm install stable
fi
PIP=$(command -v pip)
if [ ! -z "$PIP" ]; then
  if [ $PIP == $HOME/.local/bin/pip ]; then
    echo ""
    echo "Updating pip..."
    pip install -U pip
    AWS=$(command -v aws)
    if [ ! -z "$AWS" ]; then
      if [ $AWS == $HOME/.local/bin/aws ]; then
        echo ""
        echo "Updating aws-cli..."
        pip install -U awscli
      else
        echo "Unable to update aws since it is not installed for the local user."
      fi
    fi
  else
    echo "Unable to update pip since it is not installed for the local user."
  fi
fi
PLATFORM=$(command -v platform)
if [ ! -z "$PLATFORM" ]; then
  echo ""
  echo "Updating platform..."
  platform self-update --yes
fi
RVM=$(command -v rvm)
if [ ! -z "$RVM" ]; then
  echo ""
  echo "Updating rvm..."
  rvm get head
  rvm reload
  rvm get stable --auto
fi
